version: '3.2'
services:
        las:
                image: iexechub/sconecuratedimages-iexec:las-v3.0
                devices:
                        - "/dev/isgx:/dev/isgx"
                ports:
                        - target: 18766
                          published: 18766
                          protocol: tcp
                          mode: host
networks:
        default:
                external:
                        name: romain-net      
